version: "3.8"
services:
  microservice1:
    image: node:alpine
    init: true
    container_name: sqs-microservice1
    volumes:
      - ./microservice1:/usr/src/app
      - ~/.aws/:/root/.aws:ro
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
    ports:
      - "3031:3031"

  microservice2:
    image: node:alpine
    init: true
    container_name: sqs-microservice2
    volumes:
      - ./microservice2:/usr/src/app
      - ~/.aws/:/root/.aws:ro
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
    ports:
      - "3032:3032"

  microservice3:
    image: node:alpine
    init: true
    container_name: sqs-microservice3
    volumes:
      - ./microservice3:/usr/src/app
      - ~/.aws/:/root/.aws:ro
    working_dir: /usr/src/app
    command: sh -c 'npm install; npm start'
    ports:
      - "3033:3033"
